import React from 'react'

export default function About() {
  return (
    <div className='py-20 px-4 max-w-6xl mx-auto'>
      <h1 className='text-3xl font-bold mb-4 text-slate-800'>About Realtor Estate</h1>
      <p className='mb-4 text-slate-700'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate eveniet harum consequuntur sapiente rerum. In rerum iure, hic labore ipsum dolorem inventore voluptatem assumenda maxime error quae, molestiae expedita dolor! Eveniet quod fugit aspernatur voluptatum id cum adipisci dicta expedita est, ex quasi similique corrupti obcaecati sequi accusantium, vel qui. Excepturi deleniti suscipit omnis ex consectetur magnam fugiat, dolores veniam corrupti sequi vero facilis dignissimos quo expedita rerum, hic voluptates repellendus adipisci harum sed ut! Sunt magnam magni molestiae possimus laudantium quo accusamus omnis dolorem aspernatur, quos laboriosam quas, soluta fugit assumenda velit dolores? Repudiandae asperiores quis delectus ipsa harum.</p>
      <p className='mb-4 text-slate-700'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate eveniet harum consequuntur sapiente rerum. In rerum iure, hic labore ipsum dolorem inventore voluptatem assumenda maxime error quae, molestiae expedita dolor! Eveniet quod fugit aspernatur voluptatum id cum adipisci dicta expedita est, ex quasi similique corrupti obcaecati sequi accusantium, vel qui. Excepturi deleniti suscipit omnis ex consectetur magnam fugiat, dolores veniam corrupti sequi vero facilis dignissimos quo expedita rerum, hic voluptates repellendus adipisci harum sed ut! Sunt magnam magni molestiae possimus laudantium quo accusamus omnis dolorem aspernatur, quos laboriosam quas, soluta fugit assumenda velit dolores? Repudiandae asperiores quis delectus ipsa harum.</p>
      <p className='mb-4 text-slate-700'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate eveniet harum consequuntur sapiente rerum. In rerum iure, hic labore ipsum dolorem inventore voluptatem assumenda maxime error quae, molestiae expedita dolor! Eveniet quod fugit aspernatur voluptatum id cum adipisci dicta expedita est, ex quasi similique corrupti obcaecati sequi accusantium, vel qui. Excepturi deleniti suscipit omnis ex consectetur magnam fugiat, dolores veniam corrupti sequi vero facilis dignissimos quo expedita rerum, hic voluptates repellendus adipisci harum sed ut! Sunt magnam magni molestiae possimus laudantium quo accusamus omnis dolorem aspernatur, quos laboriosam quas, soluta fugit assumenda velit dolores? Repudiandae asperiores quis delectus ipsa harum.</p>
    </div>
  )
}
